name: 'Aqua Security Tracee Start'
description: 'Start Runtime Security and Forensics using eBPF'
author: 'Aqua Security'
inputs:
  workdir:
    description: "Working directory for Tracee"
    required: true
    default: "/tmp/tracee"

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      docker pull simar7/tracee:latest
      docker run -d --name tracee-profiler --rm --privileged \
      -v /proc:/proc -v /boot:/boot -v /lib/modules/:/lib/modules/:ro \
      -v /usr/src:/usr/src:ro -v ${{ inputs.workdir }}:/tmp/tracee simar7/tracee:latest \
      trace --capture exec --capture profile