name: 'Aqua Security Tracee Stop and Check'
description: 'Stop & Checks Tracee results with Runtime Security and Forensics using eBPF'
author: 'Aqua Security'
inputs:
  workdir:
    description: "Working directory for Tracee"
    required: false
    default: "/tmp/tracee"

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      echo "Stopping Tracee..."
      docker kill --signal="SIGINT" tracee-profiler
      docker wait tracee-profiler

      ${{ github.action_path }}/stop.sh ${{ inputs.workdir }} ${{ github.token }}