name: 'Aqua Security Tracee Stop and Check'
description: 'Stop & Checks Tracee results with Runtime Security and Forensics using eBPF'
author: 'Aqua Security'
inputs:
  workdir:
    description: "Working directory for Tracee"
    required: false
    default: "/tmp/tracee"

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      echo "Stopping Tracee..."
      docker kill --signal="SIGINT" tracee-profiler
      docker wait tracee-profiler

      echo "Checking results..."
      cmp ${{ inputs.workdir }}/out/tracee.profile ./tracee.profile
      rc=$?
      if [ $rc -ne 0 ]; then
        echo "Differences found..."
        diff ${{ inputs.workdir }}/out/tracee.profile ./tracee.profile
        echo "Creating a commit with all changes..."
        cp ${{ inputs.workdir }}/out/tracee.profile .
        git config --global user.email "opensource@aquasec.com"
        git config --global user.name "Tracee Bot"
        gh auth login --with-token <<<'${{ github.token }}'
        git fetch --all
        git checkout -B 'tracee-profile-update' $(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
        git add tracee.profile
        git commit -m 'update tracee.profile'
        git push -f --set-upstream origin tracee-profile-update
        gh pr create --title "Updates to tracee.profile" --body "List of runtime programs executed during this pipeline run. Powered by Tracee"
        echo "PR Created"
        exit 1
      else
        echo "No profile differences found"
        exit 0